version: '3'

services:
    api:
        env_file: 
            - .env
        build:
            context: .
            dockerfile: docker/build.Dockerfile
        ports:
            - '${SERVER_PORT}:${SERVER_PORT}'
    
    unit-test:
        build:
            context: .
            dockerfile: docker/base-tests.Dockerfile
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]