version: 2.1

jobs:
  unit-test:
    machine: true
    steps:
      - checkout
      - run:
          name: creating .env
          command: echo "SERVER_PORT=${SERVER_POST}" >> .env
      - run:
          name: Unit tests
          command: make unit-test
  deploy-api:
    working_directory: ~/app
    machine: true
    steps:  
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Login docker
          command: docker login -u mayconcarleterodrigues -p ${DOCKER_PASSWORD}
      - run:
          name: Docker Build
          command: docker build -t mayconcarleterodrigues/app -f ~/app/docker/build.Dockerfile .
      - run:
          name: Pushing image to docker hub
          command: docker push mayconcarleterodrigues/app

workflows:
  version: 2
  build_and_tests:
    jobs:
      - unit-test
      - deploy-api:
          requires:
            - unit-test