version: 2.1

jobs:
  unit-test:
    machine: true
    steps:
      - checkout
      - run:
          name: create .env
          command: |
          echo "SERVER_PORT=${SERVER_POST} >> .env"
      - run:
          name: Unit tests
          command: make unit-test
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: login
          command: docker login -u mayconcarleterodrigues -p $DOCKER_PASSWORD
      - run:
          name: docker build 
          command: docker build -t mayconcarleterodrigues/app .
      - run:
          name: docker push 
          command: docker push mayconcarleterodrigues/app

workflows:
  version: 2
  build_and_tests:
    jobs:
      - unit-test
      - build:
          requires:
            - unit-test